### ISSUE TITLE
Please fix your chrome plugin!

### ISSUE THREAD

**Issue by ghost** [satsukitv/twitter-block-chain#11]
Twitter Block Chain is not work anymore, there is an only error.
Fix it quicly. I'm very upset in errors.

**Comment by ceceradio** [comment]
Hi there! You need to upgrade Chrome to version 67. It's very likely you're on version 66 which introduced a known bug. There's nothing wrong with the extension itself. If you still encounter issues after upgrading chrome to version 67, let me know.
