### ISSUE TITLE
Extension not working correctly

### ISSUE THREAD

**Issue by lia405** [satsukitv/twitter-block-chain#13]
The extension stops working after about 5.4K followers are retrieved, and when I refresh the page and try again it only goes up to 18... I waited a few hours then tried again, and again it only went up to 5.4K and then to 18 when I refreshed. I'm trying to block someone's 13.1K followers (sorry for not putting a description, I accidentally pressed enter after typing the title only).

**Comment by ceceradio** [comment]
If you are receiving only "Errors" when blocking on Chrome you will need to update to Chrome 67.

**Comment by lia405** [comment]
I checked and I'm using Chrome 67, I'm getting the impression that twitter is stopping me from going over 5K for some reason.

**Comment by ceceradio** [comment]
There are definitely API limits in place by twitter to prevent people from infinitely blocking. These rate limits are implemented by twitter and undocumented... some people have reported 8k, 10k, before the extension stops. there's not much we can do about it... a rate limit is a rate limit.
