### ISSUE TITLE
[Firefox] All requests fail while tabbed out

### ISSUE THREAD

**Issue by twilight-sparkle-irl** [satsukitv/twitter-block-chain#14]
I'm not sure if this is an API issue that's fixable, but I thought I'd note it.

**Comment by ceceradio** [comment]
not sure if this is going to be fixable. one of the tricks i've learned from chrome is that you can pull the tab out into its own window and that seems to make it keep running even if the window is in the background. not sure if this will work for firefox

**Comment by twilight-sparkle-irl** [comment]
It does, which is what I've been doing. Perhaps as a fallback mechanism it could simply pause if it gets errors and the user is tabbed out, pop up an alert(), and wait for the user to tab back in.
