### ISSUE TITLE
[Firefox] Block Chain is unable to retrieve accounts

### ISSUE THREAD

**Issue by alluringmoon31** [satsukitv/twitter-block-chain#15]
After successfully blocking a variable amount of accounts (from a few dozen to a few hundred) Twitter Block Chain will report the following error:

"There was an error retrieving more accounts. Please refresh the page and try again."

Afterwards, I am not able to even see past the first followers (or rather the last followers, I guess) of an account (usually can only see 18 accounts then). Even with a hard refresh, logging in and out of the account and trying to do so on a fresh browser install (I even installed Chrome just to test this), the problem persists. It's like twitter is blocking the requests to see the followers.

If I try to do chain block accounts using a new account I created, it works again... But also only for a certain amount of accounts. Then I have the same issue, again.

**Comment by ceceradio** [comment]
yeah that's twitter's rate limiter. there's nothing we can do to get around that. try to make sure you're only running TBC on one account at a time and on accounts that have less than 10k followers. any more than that and you'll definitely get rate limited for at least an hour.

**Comment by rifflesby** [comment]
Any idea what specifically triggers the rate limiter? Could it be gotten around by doing the blocks much more slowly, like 1 or 2 per second? I wouldn't mind having a long-term background task like that running, provided I could pause and resume if necessary.
