### ISSUE TITLE
You know this violates TOS, right?

### ISSUE THREAD

**Issue by PedroAlucinante** [satsukitv/twitter-block-chain#16]
This add-on appears to work by scraping Twitter via the API calls used by twitter's web interface rather than using Twitter's public API.  You should probably fix that before you get banned.

**Comment by ceceradio** [comment]
This tool's been around for years and twitter is 100% aware of its existence. It serves a vital purpose and hits up against the same rate limit requests that any other automation or user interaction would. I've spoken to a twitter engineer about API endpoints that would make a tool like this possible on the public APIs; however, that's a pretty low priority for them.

Considering what you're asking though, it sounds like you're mad. Are you mad?

**Comment by PedroAlucinante** [comment]
Although I understand the intent, the tool boils down to guilt by association.  Since following someone is a voluntary action, I can vaguely understand wanting to block all the followers of a troll account, but allowing the same action on the "following" page makes less than zero sense; I don't get a choice as far as who follows me, and accounts that engage in harassment frequently follow their targets. You're compounding the problem by including that feature.
