### ISSUE TITLE
[Chrome] Blocking doesn't work -- some tests and ideas

### ISSUE THREAD

**Issue by stypr** [satsukitv/twitter-block-chain#21]
I get the same problem with #5 now.

So as for now, I decided to do some basic tests on this and try to figure out the issue.
So I was checking this original [blockchain.js#L186](https://github.com/satsukitv/twitter-block-chain/blob/master/js/blockchain.js#L186) and I found out that the parameter changed so I decided to change the data and try it:

```
        data: {
            authenticity_token: authenticity_token,
			challenges_passed: false,
			handles_challenges: "1",
            impression_id: "",
            user_id: String(user_id),
            //block_user: true,
            //report_type: "",
            //screen_name: user_name,
	},
```

it still didn't work out well 😞 

I've also added an header to ajax request, it still didn't work out well.
```
headers: { "x-twitter-active-user": "yes", }
```

For now, the only header left between the original request and the app's request is the `Origin` header. 
![picture](http://up.harold.kim/Tckk0tNjP1H7BSke)

It is certain that the Twitter might check the `Origin` header for the security issue. But usually changing `Origin` header is not allowed from script by default. 

So if there's any way find a way to change the Origin, we can get this problem fixed somehow.

I think there are websites that says `chrome.webRequest.onBeforeSendHeaders.addListener` can be used to modify the `Origin` header but I couldn't make it work.. can you find a way about it?

**Comment by ceceradio** [comment]
duplicate of #24
