### ISSUE TITLE
Unable to find accounts to block while using new Twitter beta

### ISSUE THREAD

**Issue by Kataract** [satsukitv/twitter-block-chain#24]
I opted-in to Twitter's new layout and they've changed the followers page from a card layout to a list-esque layout.  The selectors can no longer match what the extension expects.

The list appears to be in a `section[role="region"]`, but it's using auto-generated React classes that make it pretty impenetrable to guess what's where (and is also aggressively clouded with `div`s.  Sample selector for the text of someone's handle, generated by Firefox devtools:

```
.rn-ndvcnb.rn-gxnn5r.rn-fnigne.rn-13yce4e.rn-deolkf.rn-111h2gw.rn-1471scf.rn-18u37iz.rn-14xgk7a.rn-a023e6.rn-o11vmf.rn-16dba41.rn-ad9z0x.rn-p1pxzi.rn-11wrixw.rn-61z16t.rn-1mnahxq.rn-dnmrzs.rn-bcqeeo.rn-11yh6sk.rn-buy8e9.rn-1mdbw0j.rn-gy4na3.rn-9aemit.rn-wk8lta.rn-bauka4.rn-1udbk01.rn-3s2u2q.rn-qvutc0 {
}
```

**Comment by goranbeg** [comment]
I have same problem. :(

**Comment by ceceradio** [comment]
Working on it, friends! should have an update soon...

**Comment by ceceradio** [comment]
new update coming soon https://github.com/satsukitv/twitter-block-chain/pull/27
