### ISSUE TITLE
Receipts page seems to stop updating

### ISSUE THREAD

**Issue by catamorphism** [satsukitv/twitter-block-chain#26]
I just discovered the "options" context menu and the "receipts" page. I was initially excited to see it, but then when I sorted by "Date Blocked" I noticed a couple things:

- it doesn't actually sort by date (the first and last pages are dated Aug 9, 2017, but if I click a few pages back or forwards, I see entries from Aug 14, 2017; it actually just seems to sort the table by username even if I click on the date sorting arrow in the "Connection To" or "Date Blocked" columns)

- even considering that, it seems to have stopped adding new users at some point (it shows I have 49,572 users blocked, but it must be more than that because (a) the only entries I can see are from 2017; (b) when I use the search box to search for a substring of a user who I know I blocked through the block chain extension, I do get some results, but not the one I'm looking for, and the results I do get are all from 2017.)

Is there a maximum number of users the "receipts" page can handle? I really want receipts :(

**Comment by catamorphism** [comment]
As a data point, when I exported my block list from Twitter, I see 464907 entries, and I'm pretty sure the majority are accounts I've blocked through the block chain extension.

**Comment by ceceradio** [comment]
the first fix for this will come in https://github.com/satsukitv/twitter-block-chain/pull/27 which will allow the receipts page to be more easily browsable. i will try and improve this page overtime, but the datatables extension i was using just wasn't able to handle the massive quantity of data i was getting.

**Comment by catamorphism** [comment]
Great, thanks! I understand that I'm probably stressing the extension under a larger amount of data than it was originally intended for :)
