### ISSUE TITLE
Blocking stops after a couple of accounts

### ISSUE THREAD

**Issue by DrMcCoy** [satsukitv/twitter-block-chain#28]
Since the last update, 1.8.0, Twitter Block Chain doesn't work correctly anymore, especially with larger account where I have already blocked a good part.

"Found" and "Already Blocked" keep counting up, but "Blocked" stalls early one, despite the difference between the first two growing.

In the end, the tally might look like this:

```
Found: 2046

Skipped: 0

Already Blocked: 1591

Blocked: 5

Total: 2046

Errors: 0
```

I'm on Firefox 66.0.1 (64-bit), on Gentoo Linux.

**Comment by DrMcCoy** [comment]
Same with exporting. 

For example:
```
Found: 365

Skipped: 0

Exported: 18

Total: 365
```

And the final list really has only 18 entries.

**Comment by SKuNKW0RXx** [comment]
Can confirm this happens when scanning an account's followers.

> Found : XXXX(total number of followers)
> 
> Skipped: 0
> 
> Exported: 18
> 
> Total : XXXX(total number of followers)

And my final entry has only 18 accounts.  I even manually scrolled through 1.9K accounts on a follower list to help propagate the list.  Still had no effect on scanning.

**Comment by DrMcCoy** [comment]
When I first manually load a few pages of followers, it often works (but notalways).

It looks like it stops when the blocking catches up to when followers are still gathered, but the block queue is empty (because there are lots of accounts already blocked).

**Comment by ceceradio** [comment]
@DrMcCoy is this on the old twitter UI or the new twitter UI?

**Comment by DrMcCoy** [comment]
Eeerm, I think the old? I haven't noticed any big changes recently, or are they more subtle? How can I tell?

**Comment by SKuNKW0RXx** [comment]
I've checked using the new UI.  I also used a chrome extension called "Twitter DeBubbler" to take it back to the old UI.  There was no change on how many accounts it could find.  It still stopped at 18.

I also tried the mobile version mobile.twitter.com and it couldn't recognize the accounts to list them.

**Comment by DrMcCoy** [comment]
Well, okay, *now* I see what you mean by new UI. I've been forced into it now.

And yes, it seems like this extension works far better with the new UI in general. It seems you even changed how followers are enumerated, because now it grabs 5000 at once instead of 18, and it's not running into the 5000-odd limit (which, I assume, was 300 requests at 18 = 5400?)

I guess now that the new UI is (globally?) being rolled out, and even that opt-out link that worked for a day doesn't work anymore, this issue can be closed?

**Comment by ceceradio** [comment]
sweet! yeah the new twitter UI is weird but it at least lets us block more people 😈

**Comment by SKuNKW0RXx** [comment]
So, I hate to comment on a closed thread, but what was the fix action because I'm still stuck at 18.

**Comment by ceceradio** [comment]
@ghost0001 if you could either open another issue with some screenshots or something that'd help. since there are two UIs floating around its hard to tell where the bug is but it doesnt seem to be in the new UI.
