### ISSUE TITLE
Firefox Update?

### ISSUE THREAD

**Issue by cicifluff** [satsukitv/twitter-block-chain#3]
Will there be a firefox update for this add-on? I can only block 18K accounts on chrome. I'd like to see if Firefox is any more effective. Unfortunately, I have Firefox 58 and the current app is for an earlier version.

**Comment by ceceradio** [comment]
@cicifluff it's a limitation of twitter, rather than chrome/firefox. we can only block so many accounts with a web token before it starts rate limiting.

**Comment by ceceradio** [comment]
The Firefox version is now up to date :^)
