### ISSUE TITLE
Count of blocks = count of errors; nothing is getting blocked

### ISSUE THREAD

**Issue by hockeyjamie** [satsukitv/twitter-block-chain#30]
This seems to be related to #5 which is now closed.  Every time I run block chain I am getting the count of blocks = count of errors and no blocks actually occur.  It had been working previously.  It seems like it stopped working around Tuesday May 7.  Let me know what other info I can provide to you.

**Comment by ceceradio** [comment]
Is this on the old twitter UI or new twitter UI?

**Comment by hockeyjamie** [comment]
Hi.  I ran it on my laptop using Chrome, so it's the web site, not the app.  When did the UI change?

**Comment by ceceradio** [comment]
can you post a screenshot of the whole page when this problem happens? i can tell what UI you're on based on what it looks like :^)

**Comment by hockeyjamie** [comment]
Hi.  Here you go.  I took the screen shot while it was running.
![image](https://user-images.githubusercontent.com/50087339/57882058-cefc2c00-77f0-11e9-97bf-633840cdc3eb.png)

**Comment by ikesnopes** [comment]
I have this problem too.

**Comment by madethisjustfortwitterblockchain** [comment]
when i inspect the network part of the site, i get "your account cannot perform this action", if that helps

**Comment by ceceradio** [comment]
so, you're currently using the "old" twitter UI which will be deprecated soon. try using twitter block chain on mobile.twitter.com or on firefox. let me know if that works @madethisjustfortwitterblockchain @ikesnopes @hockeyjamie

**Comment by ikesnopes** [comment]
Where do we get twitter block chain for android mobile?

**Comment by ceceradio** [comment]
@ikesnopes twitter block chain only exists for chrome and firefox on PC/Mac.

**Comment by ikesnopes** [comment]
Thank you, I misunderstood and thought it was available for Android, it's
working fine for me in firefox! :)

**Comment by gaeulbyul** [comment]
@ikesnopes Yandex browser and Firefox for Android can install Twitter-block-chain extension and it works pretty well.

**Comment by hockeyjamie** [comment]
This seems to be functioning once again.
