### ISSUE TITLE
Requesting API from mobile.twitter.com domain blocked by Chrome

### ISSUE THREAD

**Issue by gaeulbyul** [satsukitv/twitter-block-chain#31]
Running TBC from `mobile.twitter.com` is blocked with this console message:

> Cross-Origin Read Blocking (CORB) blocked cross-origin response <URL> with MIME type application/json. See https://www.chromestatus.com/feature/5629709824032768 for more details.

seems changes on Chrome prevents ajax request. https://www.chromium.org/Home/chromium-security/extension-content-script-fetches

running in `twitter.com` domain (with new UI) works normally. also, running in Firefox works normally. (both `twitter.com` and `mobile.twitter.com`)

**Comment by ceceradio** [comment]
Hi @gaeulbyul 💙! Can you see if this works? https://github.com/satsukitv/twitter-block-chain/pull/32

**Comment by gaeulbyul** [comment]
Great! It works well! :+1:  :blue_heart:

**Comment by ceceradio** [comment]
sweet thank you!!! just uploaded the new version.
