### ISSUE TITLE
Blocking stops exporting at 18

### ISSUE THREAD

**Issue by SKuNKW0RXx** [satsukitv/twitter-block-chain#38]
This issue was address in a closed thread so I'm opening a new one with screen caps of my UI.  IDK what UI for Twitter I am on nor how to check it at the moment.  I am updated to the latest version of the extension and it's failing to grab more than 18 accounts.  

[Link to screencaps](https://imgur.com/a/ylTLUWT)

**Comment by ceceradio** [comment]
please use mobile.twitter.com for the tool. the version of twitter on the web you are using is very close to being defunct and is not worth the time to fix bugs on.
