### ISSUE TITLE
Running Extension Now Necessitates Cache Clear

### ISSUE THREAD

**Issue by padmanjones** [satsukitv/twitter-block-chain#39]
I had been running into the same issue that a lot of people had reported where you could only block like ~8,000 accounts in one go; while I can now block up to ~80,000 accounts at once, any time I run the extension, Twitter will then throw an error ("Something went wrong") and refuse to actually load the timeline unless I clear my browsing data and then log back in. 

Also, on some occasions after I've run the extension, going to twitter.com will throw the login page, as if I hadn't already been logged in, but no matter how many times I enter my user name/password, it'll keep returning me to the login screen. Again, at that point, I have to clear my browsing data before I can get back in.

**Comment by Oregoncat** [comment]
I have pretty much the same issue. It won't retrieve more than 89,999 accounts at all, and usually generates an error along the way when there's more. Then it requires a cache clear/new login to access Twitter again.

**Comment by wkitty42** [comment]
i've seen this as well... especially when processing accounts with 100K+ followers/follows...

**Comment by theGr33nRouu** [comment]
Chiming in for feedback. Same issue when it was working at all for me.

**Comment by ceceradio** [comment]
The limit is API imposed. Twitter enforces that limit, which is probably why you're having issues logging back into Twitter. If clearing your cache is working then I recommend just doing that.

**Comment by theGr33nRouu** [comment]
I was more concerned with the last half of my email; the ext isn't working
at all. Ext shows an error on every run, but the Chrome dev tools doesn't
show errors in the console or network tabs.

The API limit I understand. I mentioned those issues for context but I
suppose it was unnecessary and confusing.
