### ISSUE TITLE
Whitelist/Appeal/False-Positive process or ideas?

### ISSUE THREAD

**Issue by inversephase** [satsukitv/twitter-block-chain#42]
Up-front disclosure: I was made aware of this plugin because I was blocked by it.

Being a level-headed individual, I understand the need to have piece of mind, and I get that social media might need a colon cleanse. However, I'm not a troll (except for an 8-bit harlem shake video back in 2013 that I claimed was a new release) and I don't subscribe to any personal policies that I think would get me a tier-1 block (or whatever you want to call the people that you run the plugin on their page). I was probably blocked at a lower tier; ie. I followed someone that said something dumb or racist or whatever on twitter, and got caught in the crossfire or was an unfortunate casualty of a mass block.

Here is a thread where I found out the plugin was being used and deduced that it's the only way I could have been blocked, for clarification:
https://mobile.twitter.com/AmyDentata/status/1168303972626513920

And here's another person that appears to have been accidentally blocked, I'm guessing possibly the same thing happened:
https://mobile.twitter.com/Frumple_James/status/1168860783436021760

I've done a lot of thinking on this. It's not an awful assumption to think that someone might be following an unkind individual on twitter because they are also unkind, and sure, perhaps both of those people deserve to be blocked.

However, there are other reasons that someone might follow a troll. In my case, I'm following a LOT of people. In 2012 I released an album that was popular and when a lot of people started following me later on, I decided I would follow people back. This is an old mentality and I have since stopped, but there are certainly a decent number of us out there.  Another thought is that someone (a kind individual) might be monitoring and logging an unkind individual's tweets. 

So, even if there are only a few false-positives, I think that the number is higher than one might expect, and there should be a way to mitigate any damage caused by a mass block. #23 shows us that people do indeed mistakenly run the plugin on the wrong person or later find out the block was by mistake. 

I don't have a solution for this, because I don't want to sound presumptuous - I don't know your goals for your project, and I don't want to come out of nowhere and tell you how to run your project. I figured I would put forth some ideas that spring to mind and we could talk about them here:

- Undo feature, as mentioned in issue #23 
- Whitelist of false-positives (perhaps could be integrated with #36 ?)
- Appeals process so that somehow someone who got blocked accidentally could be added to whitelist, or perhaps at least figure out what happened - ("you were blocked because you follow X") 

Anyway, hopefully this can be the beginning of a productive discussion about what to do, thank you for reading!

**Comment by roycewilliams** [comment]
Hey, @inversephase ! (Random side note: I'm a fan of your work here, especially Pretty Eight Machine - brilliant stuff!)

I'm not a dev on this project, but I am a very active user, and you've politely and thoroughly summarized some of the complexity here. 

I've definitely blocked people that I wouldn't have chosen to, but it's less frequent for me than it may be for others. I really only use the extension to block everyone who's following an obvious bot - which is almost always thousands of other bots. So for me, the only false positives are accounts that indiscriminately follow back in bulk, through brand-management/automation/SEO tools, and so I'm willing to handle the occasional false positive (and also have info in my bio to guide people towards how to contact me if they've been blocked in error).

I think that some users use Twitter Block Chain less surgically, and the result is definitely a higher rate of false positives.

As to your (constructive) suggestions ... undo and whitelist are great ideas that I totally support. The appeals process, however, would have to be implemented by Twitter itself - in other words, once someone is blocked, how the block appears and is managed is wholly owned by the Twitter platform directly and this extension has no way to intervene or manage that. Only by putting something in the blocker's bio or pinned Tweet can anything be communicated back to the blocker (And then only if they use a private/incognito window or separate browser to view that profile while not logged into Twitter).

**Comment by inversephase** [comment]
Hey, thanks for the kind words on my work - it's perhaps bitter irony that Pretty Eight Machine is the thing that caused me to grow, and yet, now, because I was so excited to auto-followback, is now the thing that is keeping me from growing. 

Anyway, to matters at hand: 

One thing I failed to mention is that I absolutely agree with your "less surgical" line; I was going to mention that myself but I was afraid of my issue/comment already getting too long. In addition, I think many people — even though they fully understand what the tool is and what it does — do not realise the repercussions of their actions until it is too late. Admittedly, I don't use the tool, but perhaps as an initial measure, a warning dialog saying "warning, you're seriously about to block 8000 people" or whatever and giving the user the option to "just block this person" in addition to ok and cancel in the dialog would be good? I don't know if this already exists. 

For the appeals process, I have ideas. You're right nobody could "get through" the twitter block, but what about this:

If someone thinks they're blocked by TBC (sorry if this reads as time-base corrector to you, my brain is doing weird stuff), or would like a chance to prove that they are human and not a troll, they follow something like @TBC_appeals on twitter. The account automatically DMs them a place they can fill out a form to be considered for whitelisting, and a human would probably have to volunteer to go through these. Optionally TBC could report the second-tier names that were blocked to uh, somewhere, and who they were blocked because of (the initial offending party). Although there might be privacy concerns there, but a dialog could provide the enduser option of not supplying their own name ("remain anonymous" checkbox or something) if they're worried about blowback. And some of them might not want to remain anonymous, which if that were so, we'd have a way to find out if you're blocked by TBC or some other method instead.

This is just a braindump / initial idea, it could be shaped to fit the need of users or anyone developing on TBC.

Thanks again to anyone reading.

**Comment by ceceradio** [comment]
tool already has a whitelist and receipts. closing

**Comment by inversephase** [comment]
Can you please explain how the whitelist and receipts in your tool would help resolve the problem described?
