### ISSUE TITLE
Twitter longing me off my account after using it once

### ISSUE THREAD

**Issue by sashacool185** [satsukitv/twitter-block-chain#48]
I used the extension once on Chrome, now logs me off at random. I'm afraid I can get banned by twitter, as one other user on the reviews on google web store had the same problem as mine and twitter banned them.

**Comment by theGr33nRouu** [comment]
I also encountered this issue.

**Comment by ceceradio** [comment]
I also encountered the log off, but I was able to log back in and use it again. I've been using this tool for years and haven't been banned. To minimize your risk of getting banned or suspended for using this (which I've heard no credible reports of that happening) only use it in response to imminent dogpiling.
