### ISSUE TITLE
Totally breaks twitter site on chromebook

### ISSUE THREAD

**Issue by ebeeb** [satsukitv/twitter-block-chain#79]
Every time I use this, it logs me out of twitter and I have to erase cookies to be able to sign back in. But the more I use it, eventually I am completely unable to sign back into to Twitter on Chrome again at all - I just get twitter error messages and the site no longer loads, at which point erasing cookies does nothing.

I've had this happen on two separate computers and am now completely locked out of Twitter on Chrome browsers on both Chromebook laptops. Even removing the app from Chrome entirely does not make a difference - Twitter remains unavailable to me.

**Comment by alealia** [comment]
I've had this problem too, ever since installing BlockChain.

Every time I run it, I then can't load any feed or options in Twitter and refreshing the page results in an error / me being logged out and being prompted to log back in. I often have to clear my cookies to fix this. It's very frustrating as I'm just trying to better my experience on the site.

**Comment by Gabriel-p** [comment]
I get this after 500 blocks. I need to delete cookies and re-log. It looks like something done by Twitter rather than an issue with the extension.

**Comment by DrBruceLong** [comment]
Yes. It appears that Twitter has implemented a countermeasure. Presumably they have algorithms to detect the rate and number of blocks. They disable the twitter account on the Browser using cookies somehow. I was able to circumvent this by logging in with Incognito. I have also blocked cookies for Twitter.com only in chrome settings, but I am not sure how effective this was.

**Comment by indialeigh** [comment]
Clear your search history every time you get logged out of the website. This helped me round the obstacle.

**Comment by Super-Dope999** [comment]
Twitter and these people should work together not against each other - trolls are intense.

**Comment by digitaldraco** [comment]
> Twitter and these people should work together not against each other - trolls are intense.

Agreed! Two years and it still does this. I'm using Chrome on a MacBook.

And when I tried to use it on someone with over 1,000 followers, it says it has an error loading users?
