### ISSUE TITLE
Block Chain not currently allowing blocks

### ISSUE THREAD

**Issue by AnonymouslyAnonymous** [satsukitv/twitter-block-chain#9]
Known issue or troubleshooting steps anyone?

![screen shot 2018-05-19 at 9 39 10 pm](https://user-images.githubusercontent.com/39448827/40274742-255fcef0-5bad-11e8-9d03-19fc944ea949.png)

**Comment by ceceradio** [comment]
hey there! this is a duplicate of #5, please check out that issue for more information (see the bottom 2 posts)
